# Generated by Django 2.2.5 on 2019-09-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190617_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='failed',
            name='game_user',
            field=models.ManyToManyField(related_name='game_failed', to='login.User'),
        ),
        migrations.AddField(
            model_name='intro',
            name='game_user',
            field=models.ManyToManyField(related_name='game_intros', to='login.User'),
        ),
        migrations.AddField(
            model_name='responses',
            name='game_user',
            field=models.ManyToManyField(related_name='game_responses', to='login.User'),
        ),
        migrations.AddField(
            model_name='responses',
            name='type',
            field=models.CharField(default='', max_length=155),
        ),
    ]
