# Generated by Django 2.2.5 on 2019-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190913_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='max_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='min_level',
            field=models.IntegerField(null=True),
        ),
    ]
