# Generated by Django 2.2.5 on 2019-09-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rules', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=175)),
                ('description', models.CharField(max_length=255)),
                ('sample_code', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
                ('solved', models.BooleanField(default=False)),
                ('chapter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise', to='game.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='game.GameUser'),
        ),
    ]
