# Generated by Django 2.1.2 on 2019-06-17 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Failed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('looked_up', models.IntegerField()),
                ('recognized', models.CharField(max_length=30)),
                ('token', models.CharField(default='', max_length=30)),
                ('friends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='responses',
            name='user',
            field=models.ManyToManyField(related_name='responses', to='login.User'),
        ),
        migrations.AddField(
            model_name='intro',
            name='user',
            field=models.ManyToManyField(related_name='intros', to='login.User'),
        ),
        migrations.AddField(
            model_name='failed',
            name='user',
            field=models.ManyToManyField(related_name='failed', to='login.User'),
        ),
    ]
